/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chau;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author giovanni
 */
public class TelaPrincipal extends javax.swing.JFrame {
    private DefaultTableModel DfltTable;
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        DfltTable =(DefaultTableModel) Tbl.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl = new javax.swing.JTable();
        TxtOrdem = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtDesc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtHoras = new javax.swing.JTextField();
        BtnAdd = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        BtnGrafico = new javax.swing.JButton();
        BtnRem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"0", "Selec. Madeira", "3"},
                {"1", "Talho (Peç Curva)", "4"},
                {"1", "Talho (Assento)", "6"},
                {"1", "Talho (Encosto)", "7"},
                {"1", "Talho (Braço)", "3"},
                {"0", "Sel. Tecido", "1"},
                {"6", "Costura (Almofada)", "2"},
                {"3.4", "JUnç (Enc e Assen)", "2"},
                {"5.8", "Coloc (Braço)", "2"},
                {"2.8", "Coloc (Peç Curva)", "3"},
                {"9.10", "Aplic Verniz", "5"},
                {"7.11", "Coloc (Almofada)", "0.5"}
            },
            new String [] {
                "Ordem", "Descrição", "Horas"
            }
        ));
        jScrollPane1.setViewportView(Tbl);
        if (Tbl.getColumnModel().getColumnCount() > 0) {
            Tbl.getColumnModel().getColumn(0).setResizable(false);
            Tbl.getColumnModel().getColumn(0).setPreferredWidth(70);
            Tbl.getColumnModel().getColumn(1).setResizable(false);
            Tbl.getColumnModel().getColumn(1).setPreferredWidth(400);
            Tbl.getColumnModel().getColumn(2).setResizable(false);
            Tbl.getColumnModel().getColumn(2).setPreferredWidth(80);
        }

        jLabel1.setText("Ordem");

        jLabel2.setText("Descrição");

        jLabel3.setText("Horas");

        BtnAdd.setText("Adicionar");
        BtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAddActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        BtnGrafico.setText("Gerar Gráfico");
        BtnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGraficoActionPerformed(evt);
            }
        });

        BtnRem.setText("Remover");
        BtnRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(TxtOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnRem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(BtnGrafico)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnRem))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BtnGrafico, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddActionPerformed
        if (TxtOrdem.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo de Ordem não pode estar vazio");
        } else if (TxtDesc.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo de Descrição não pode estar vazio");
        } else if (TxtHoras.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "O campo de Horas não pode estar vazio");
        } else {
            DfltTable.addRow(new Object[]{TxtOrdem.getText(), TxtDesc.getText(), TxtHoras.getText()});
            Tbl.setModel(DfltTable);
       
            
            TxtOrdem.setText("");
            TxtDesc.setText("");
            TxtHoras.setText("");
            BtnGrafico.setEnabled(true);
        }
        
        
    }//GEN-LAST:event_BtnAddActionPerformed

    private void BtnRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRemActionPerformed
        if (Tbl.getSelectedRow() <= -1) {
            JOptionPane.showMessageDialog(rootPane, "Selecione um campo antes");
        } else {
            Tbl.remove(Tbl.getSelectedRow());
            DfltTable.removeRow(Tbl.getSelectedRow());
            if (Tbl.getRowCount() == 0) {
                BtnGrafico.setEnabled(false);
            }   
        }
        
    }//GEN-LAST:event_BtnRemActionPerformed

    private void BtnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGraficoActionPerformed
        for (int i=0;i< Tbl.getRowCount();i++){
            XYLineChartExample.Ordem.add((String) Tbl.getValueAt(i, 0));
            XYLineChartExample.Desc.add((String) Tbl.getValueAt(i, 1));
            XYLineChartExample.Horas.add((String) Tbl.getValueAt(i, 2));
        }
        XYLineChartExample.Execute();
    }//GEN-LAST:event_BtnGraficoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdd;
    private javax.swing.JButton BtnGrafico;
    private javax.swing.JButton BtnRem;
    private javax.swing.JTable Tbl;
    private javax.swing.JTextField TxtDesc;
    private javax.swing.JTextField TxtHoras;
    private javax.swing.JTextField TxtOrdem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
